In [98]:
# Data Manipulation Libraries
import pandas as pd
import numpy as np

# Data Visualization Libraries
import matplotlib.pyplot as plt
import seaborn as sns

# Ignore Warnings
import warnings
warnings.filterwarnings("ignore")

# Preprocessing Libraries
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# Deep Learning Libraries
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

# Model Evaluation
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Save Preprocessor
import pickle
import os

In [99]:
df = pd.read_csv("cost-analysis.csv")
df

     UsageDate                ServiceName     CostUSD          Cost Currency
0   2023-05-01                 Automation    0.001000      0.081771      INR
1   2023-05-01                  Azure DNS    0.500348     40.914076      INR
2   2023-05-01                  Bandwidth  127.770719  10447.971394      INR
3   2023-05-01                    Storage  134.504502  10998.601241      INR
4   2023-05-01           Virtual Machines   13.987309   1143.759767      INR
..         ...                        ...         ...           ...      ...
84  2024-04-01                 Logic Apps    0.003708      0.308808      INR
85  2024-04-01                    Storage  152.335920  12688.249184      INR
86  2024-04-01           Virtual Machines   22.328693   1859.784719      INR
87  2024-04-01  Virtual Machines Licenses   27.547339   2294.452273      INR
88  2024-04-01            Virtual Network   26.599421   2215.498999      INR

[89 rows x 5 columns]

In [100]:
df.head()

    UsageDate       ServiceName     CostUSD          Cost Currency
0  2023-05-01        Automation    0.001000      0.081771      INR
1  2023-05-01         Azure DNS    0.500348     40.914076      INR
2  2023-05-01         Bandwidth  127.770719  10447.971394      INR
3  2023-05-01           Storage  134.504502  10998.601241      INR
4  2023-05-01  Virtual Machines   13.987309   1143.759767      INR

In [101]:
df.shape

(89, 5)

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89 entries, 0 to 88
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   UsageDate    89 non-null     object
 1   ServiceName  89 non-null     object
 2   CostUSD      89 non-null     float64
 3   Cost         89 non-null     float64
 4   Currency     89 non-null     object
dtypes: float64(2), object(3)
memory usage: 3.6+ KB

In [103]:
df.describe()

          CostUSD          Cost
count   89.000000     89.000000
mean    47.157293   3905.133202
std     56.253490   4658.406713
min      0.000000      0.000000
25%      0.484221     40.309546
50%     23.789508   1952.895445
75%    123.555142  10138.471661
max    154.816673  12887.907485

In [104]:
df.isnull().sum()

UsageDate      0
ServiceName    0
CostUSD        0
Cost           0
Currency       0
dtype: int64

In [105]:
df.duplicated().sum()

np.int64(0)

In [106]:
df.columns

Index(['UsageDate', 'ServiceName', 'CostUSD', 'Cost', 'Currency'], dtype='object')

In [107]:
df.dtypes

UsageDate       object
ServiceName     object
CostUSD        float64
Cost           float64
Currency        object
dtype: object

In [108]:
df["UsageDate"] = pd.to_datetime(df["UsageDate"])

In [109]:
df["Year"] = df["UsageDate"].dt.year
df["Month"] = df["UsageDate"].dt.month
df["Day"] = df["UsageDate"].dt.day

In [110]:
df = df.drop("UsageDate",axis=1)

In [111]:
X = df.drop("Cost", axis=1)
y = df["Cost"]

In [112]:
num_cols=X.select_dtypes(exclude="object").columns
cat_cols=X.select_dtypes(include="object").columns

In [113]:
print(num_cols)
print(cat_cols)

Index(['CostUSD', 'Year', 'Month', 'Day'], dtype='object')
Index(['ServiceName', 'Currency'], dtype='object')

In [114]:
num_pipeline = Pipeline(steps=[("imputer",SimpleImputer(strategy="median")),
        ("scaler",StandardScaler())])

In [115]:
cat_pipeline = Pipeline(
    steps=[
        ("imputer",SimpleImputer(strategy="most_frequent")),
        ("onehotencoder",OneHotEncoder(handle_unknown="ignore"))
    ]
)

In [116]:
preprocessor = ColumnTransformer(
    [
        ("num_pipeline",num_pipeline,num_cols),
        ("cat_pipeline",cat_pipeline,cat_cols)
    ]
)

In [117]:
X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [118]:
print(X_train.columns)

Index(['ServiceName', 'CostUSD', 'Currency', 'Year', 'Month', 'Day'], dtype='object')

In [119]:
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

In [120]:
with open("preprocessor.pkl","wb") as file:
    pickle.dump(preprocessor,file)

In [121]:
model = Sequential()
model.add(Dense(128, activation="relu", input_dim=X_train.shape[1]))
model.add(Dense(64, activation="relu"))
model.add(Dense(32, activation="relu"))
model.add(Dense(1, activation="linear"))

In [122]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 128)                 │           1,792 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 64)                  │           8,256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 12,161 (47.50 KB)

 Trainable params: 12,161 (47.50 KB)

 Non-trainable params: 0 (0.00 B)

In [123]:
model.compile(
    optimizer="adam",
    loss="mse",
    metrics=["mae"]
)

In [126]:
early_stopping = tf.keras.callbacks.EarlyStopping(monitor="val_loss",patience=10,restore_best_weights=True)

In [127]:
history = model.fit(X_train,y_train,validation_split=0.2,epochs=100,batch_size=32,callbacks=[early_stopping],verbose=1)

Epoch 1/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 2s 372ms/step - loss: 42724992.0000 - mae: 4426.2397 - val_loss: 29020968.0000 - val_mae: 3511.4949
Epoch 2/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - loss: 42724160.0000 - mae: 4426.1543 - val_loss: 29020380.0000 - val_mae: 3511.4307
Epoch 3/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 42723448.0000 - mae: 4426.0942 - val_loss: 29019924.0000 - val_mae: 3511.3772
Epoch 4/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 42722900.0000 - mae: 4426.0474 - val_loss: 29019478.0000 - val_mae: 3511.3279
Epoch 5/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - loss: 42722232.0000 - mae: 4425.9917 - val_loss: 29018966.0000 - val_mae: 3511.2727
Epoch 6/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - loss: 42721528.0000 - mae: 4425.9346 - val_loss: 29018432.0000 - val_mae: 3511.2104
Epoch 7/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 42720740.0000 - mae: 4425.8716 - val_loss: 29017844.0000 - val_mae: 3511.1516
Epoch 8/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 42719972.0000 - mae: 4425.8159 - val_loss: 29017166.0000 - val_mae: 3511.0833
Epoch 9/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 42718936.0000 - mae: 4425.7539 - val_loss: 29016406.0000 - val_mae: 3511.0061
Epoch 10/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - loss: 42717960.0000 - mae: 4425.6929 - val_loss: 29015538.0000 - val_mae: 3510.9175
Epoch 11/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 42716728.0000 - mae: 4425.6172 - val_loss: 29014530.0000 - val_mae: 3510.8159
Epoch 12/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - loss: 42715388.0000 - mae: 4425.5430 - val_loss: 29013364.0000 - val_mae: 3510.6997
Epoch 13/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 42713928.0000 - mae: 4425.4419 - val_loss: 29012046.0000 - val_mae: 3510.5681
Epoch 14/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 42711840.0000 - mae: 4425.3232 - val_loss: 29010560.0000 - val_mae: 3510.4197
Epoch 15/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 42710076.0000 - mae: 4425.2085 - val_loss: 29008860.0000 - val_mae: 3510.2505
Epoch 16/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 42707484.0000 - mae: 4425.0581 - val_loss: 29006950.0000 - val_mae: 3510.0603
Epoch 17/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - loss: 42704836.0000 - mae: 4424.9038 - val_loss: 29004744.0000 - val_mae: 3509.8435
Epoch 18/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 42701596.0000 - mae: 4424.7119 - val_loss: 29002258.0000 - val_mae: 3509.5981
Epoch 19/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 42698268.0000 - mae: 4424.5063 - val_loss: 28999418.0000 - val_mae: 3509.3198
Epoch 20/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - loss: 42694564.0000 - mae: 4424.2764 - val_loss: 28996160.0000 - val_mae: 3509.0005
Epoch 21/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - loss: 42689996.0000 - mae: 4423.9961 - val_loss: 28992446.0000 - val_mae: 3508.6370
Epoch 22/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 42684436.0000 - mae: 4423.6577 - val_loss: 28988198.0000 - val_mae: 3508.2231
Epoch 23/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 42679116.0000 - mae: 4423.3169 - val_loss: 28983330.0000 - val_mae: 3507.7478
Epoch 24/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 42671804.0000 - mae: 4422.8804 - val_loss: 28977706.0000 - val_mae: 3507.1985
Epoch 25/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 42664392.0000 - mae: 4422.3911 - val_loss: 28971288.0000 - val_mae: 3506.5579
Epoch 26/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 42655380.0000 - mae: 4421.8564 - val_loss: 28964064.0000 - val_mae: 3505.8330
Epoch 27/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 42645880.0000 - mae: 4421.2231 - val_loss: 28955970.0000 - val_mae: 3505.0205
Epoch 28/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 42634104.0000 - mae: 4420.5249 - val_loss: 28946964.0000 - val_mae: 3504.1116
Epoch 29/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 42620856.0000 - mae: 4419.6958 - val_loss: 28936820.0000 - val_mae: 3503.0872
Epoch 30/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 42606148.0000 - mae: 4418.7998 - val_loss: 28925310.0000 - val_mae: 3501.9253
Epoch 31/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - loss: 42590036.0000 - mae: 4417.7627 - val_loss: 28912280.0000 - val_mae: 3500.6101
Epoch 32/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 42570984.0000 - mae: 4416.5894 - val_loss: 28897642.0000 - val_mae: 3499.1292
Epoch 33/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 42550168.0000 - mae: 4415.2803 - val_loss: 28881246.0000 - val_mae: 3497.4666
Epoch 34/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 42526932.0000 - mae: 4413.8833 - val_loss: 28862918.0000 - val_mae: 3495.6018
Epoch 35/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - loss: 42501216.0000 - mae: 4412.1958 - val_loss: 28842486.0000 - val_mae: 3493.5222
Epoch 36/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 42470976.0000 - mae: 4410.2925 - val_loss: 28819786.0000 - val_mae: 3491.2136
Epoch 37/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 42441800.0000 - mae: 4408.4131 - val_loss: 28794642.0000 - val_mae: 3488.6497
Epoch 38/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 42405048.0000 - mae: 4406.1353 - val_loss: 28767212.0000 - val_mae: 3485.8428
Epoch 39/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 42362044.0000 - mae: 4403.7144 - val_loss: 28737088.0000 - val_mae: 3482.7607
Epoch 40/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - loss: 42316104.0000 - mae: 4401.0044 - val_loss: 28704200.0000 - val_mae: 3479.3765
Epoch 41/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 42269080.0000 - mae: 4397.9370 - val_loss: 28668052.0000 - val_mae: 3475.6665
Epoch 42/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 42221644.0000 - mae: 4394.8638 - val_loss: 28628204.0000 - val_mae: 3471.9368
Epoch 43/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 42160684.0000 - mae: 4391.2603 - val_loss: 28584860.0000 - val_mae: 3468.3716
Epoch 44/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 42102260.0000 - mae: 4387.7881 - val_loss: 28537398.0000 - val_mae: 3465.1499
Epoch 45/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - loss: 42026068.0000 - mae: 4383.6611 - val_loss: 28486418.0000 - val_mae: 3462.3083
Epoch 46/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 41951672.0000 - mae: 4379.6729 - val_loss: 28430424.0000 - val_mae: 3459.3337
Epoch 47/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 41865644.0000 - mae: 4375.4536 - val_loss: 28369810.0000 - val_mae: 3456.0718
Epoch 48/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - loss: 41781580.0000 - mae: 4371.0103 - val_loss: 28303680.0000 - val_mae: 3452.4592
Epoch 49/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - loss: 41683340.0000 - mae: 4365.6548 - val_loss: 28232246.0000 - val_mae: 3448.4990
Epoch 50/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 41575268.0000 - mae: 4359.8013 - val_loss: 28155246.0000 - val_mae: 3444.1707
Epoch 51/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 41457976.0000 - mae: 4353.6323 - val_loss: 28072360.0000 - val_mae: 3439.4509
Epoch 52/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 41330112.0000 - mae: 4346.7412 - val_loss: 27983026.0000 - val_mae: 3434.2915
Epoch 53/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - loss: 41202900.0000 - mae: 4339.4653 - val_loss: 27886828.0000 - val_mae: 3428.6794
Epoch 54/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - loss: 41053652.0000 - mae: 4331.3203 - val_loss: 27783592.0000 - val_mae: 3422.5774
Epoch 55/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 40907652.0000 - mae: 4323.3652 - val_loss: 27672772.0000 - val_mae: 3416.0029
Epoch 56/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 40730744.0000 - mae: 4313.0083 - val_loss: 27555506.0000 - val_mae: 3408.9895
Epoch 57/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 40551288.0000 - mae: 4303.3726 - val_loss: 27430042.0000 - val_mae: 3401.4297
Epoch 58/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 40368572.0000 - mae: 4292.9238 - val_loss: 27295692.0000 - val_mae: 3393.2532
Epoch 59/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 40174072.0000 - mae: 4281.1890 - val_loss: 27153704.0000 - val_mae: 3384.5203
Epoch 60/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - loss: 39934740.0000 - mae: 4268.2017 - val_loss: 27004372.0000 - val_mae: 3375.2502
Epoch 61/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 39689660.0000 - mae: 4254.5640 - val_loss: 26846220.0000 - val_mae: 3365.3521
Epoch 62/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 39449748.0000 - mae: 4240.3774 - val_loss: 26677176.0000 - val_mae: 3354.7344
Epoch 63/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - loss: 39206456.0000 - mae: 4225.5288 - val_loss: 26496576.0000 - val_mae: 3343.2974
Epoch 64/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - loss: 38921212.0000 - mae: 4209.5698 - val_loss: 26306654.0000 - val_mae: 3331.1865
Epoch 65/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 38636060.0000 - mae: 4192.5024 - val_loss: 26105848.0000 - val_mae: 3318.2798
Epoch 66/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - loss: 38324604.0000 - mae: 4173.7183 - val_loss: 25894812.0000 - val_mae: 3304.5505
Epoch 67/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - loss: 37966260.0000 - mae: 4151.8740 - val_loss: 25674912.0000 - val_mae: 3290.0813
Epoch 68/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - loss: 37628020.0000 - mae: 4132.2939 - val_loss: 25442306.0000 - val_mae: 3274.6509
Epoch 69/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - loss: 37294752.0000 - mae: 4111.4302 - val_loss: 25196138.0000 - val_mae: 3258.2034
Epoch 70/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 36910572.0000 - mae: 4087.4956 - val_loss: 24939742.0000 - val_mae: 3240.8440
Epoch 71/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 36501796.0000 - mae: 4061.6819 - val_loss: 24673206.0000 - val_mae: 3222.5789
Epoch 72/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - loss: 36079776.0000 - mae: 4036.9316 - val_loss: 24395894.0000 - val_mae: 3203.4246
Epoch 73/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - loss: 35621756.0000 - mae: 4007.2456 - val_loss: 24106446.0000 - val_mae: 3183.1138
Epoch 74/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - loss: 35171320.0000 - mae: 3978.1665 - val_loss: 23803964.0000 - val_mae: 3161.6384
Epoch 75/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 34727764.0000 - mae: 3949.5300 - val_loss: 23488364.0000 - val_mae: 3142.3108
Epoch 76/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 34157484.0000 - mae: 3913.4087 - val_loss: 23167074.0000 - val_mae: 3124.2668
Epoch 77/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 33663296.0000 - mae: 3881.4358 - val_loss: 22829324.0000 - val_mae: 3104.9675
Epoch 78/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - loss: 33111570.0000 - mae: 3843.8452 - val_loss: 22480054.0000 - val_mae: 3084.6501
Epoch 79/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - loss: 32559238.0000 - mae: 3805.7966 - val_loss: 22118344.0000 - val_mae: 3063.4666
Epoch 80/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 32040370.0000 - mae: 3769.0662 - val_loss: 21742310.0000 - val_mae: 3041.0359
Epoch 81/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 31374992.0000 - mae: 3725.9214 - val_loss: 21361050.0000 - val_mae: 3017.7803
Epoch 82/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 30740714.0000 - mae: 3682.0144 - val_loss: 20969770.0000 - val_mae: 2993.4053
Epoch 83/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 30169450.0000 - mae: 3641.2554 - val_loss: 20563882.0000 - val_mae: 2967.7812
Epoch 84/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - loss: 29486804.0000 - mae: 3589.7192 - val_loss: 20151658.0000 - val_mae: 2941.1780
Epoch 85/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 28831090.0000 - mae: 3541.8618 - val_loss: 19726866.0000 - val_mae: 2913.1216
Epoch 86/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 28162806.0000 - mae: 3489.7456 - val_loss: 19293830.0000 - val_mae: 2883.8896
Epoch 87/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 27437690.0000 - mae: 3436.1753 - val_loss: 18856638.0000 - val_mae: 2853.7219
Epoch 88/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - loss: 26780618.0000 - mae: 3385.9419 - val_loss: 18408614.0000 - val_mae: 2822.0972
Epoch 89/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - loss: 26012622.0000 - mae: 3325.1211 - val_loss: 17959278.0000 - val_mae: 2789.5037
Epoch 90/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - loss: 25278430.0000 - mae: 3269.7727 - val_loss: 17505650.0000 - val_mae: 2755.8799
Epoch 91/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 24508026.0000 - mae: 3204.4353 - val_loss: 17047470.0000 - val_mae: 2720.8757
Epoch 92/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 23811850.0000 - mae: 3143.7366 - val_loss: 16582549.0000 - val_mae: 2684.4556
Epoch 93/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 23025562.0000 - mae: 3085.9197 - val_loss: 16117037.0000 - val_mae: 2649.5574
Epoch 94/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 22259506.0000 - mae: 3036.2937 - val_loss: 15653536.0000 - val_mae: 2631.8032
Epoch 95/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 21535708.0000 - mae: 2993.8965 - val_loss: 15185537.0000 - val_mae: 2627.0679
Epoch 96/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - loss: 20729964.0000 - mae: 2954.5176 - val_loss: 14724637.0000 - val_mae: 2622.0120
Epoch 97/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - loss: 19974194.0000 - mae: 2915.3333 - val_loss: 14265661.0000 - val_mae: 2616.1311
Epoch 98/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - loss: 19172928.0000 - mae: 2875.1797 - val_loss: 13811083.0000 - val_mae: 2609.2278
Epoch 99/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 18455554.0000 - mae: 2836.3474 - val_loss: 13352554.0000 - val_mae: 2601.0955
Epoch 100/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 17760860.0000 - mae: 2804.0750 - val_loss: 12898142.0000 - val_mae: 2591.8477

In [128]:
loss, mae = model.evaluate(X_test, y_test)

print("Loss :", loss)
print("MAE :", mae)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 12159334.0000 - mae: 2260.8611
Loss : 12159334.0
MAE : 2260.861083984375

In [129]:
model.save("model.keras")